# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='spike_wave.proto',
  package='',
  serialized_pb='\n\x10spike_wave.proto\"R\n\x0fSpikeWaveBuffer\x12\x12\n\nchannel_id\x18\x01 \x01(\x05\x12\x12\n\ntime_stamp\x18\x02 \x01(\x03\x12\x17\n\x0bwave_sample\x18\x03 \x03(\x02\x42\x02\x10\x01')




_SPIKEWAVEBUFFER = descriptor.Descriptor(
  name='SpikeWaveBuffer',
  full_name='SpikeWaveBuffer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='channel_id', full_name='SpikeWaveBuffer.channel_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time_stamp', full_name='SpikeWaveBuffer.time_stamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wave_sample', full_name='SpikeWaveBuffer.wave_sample', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=102,
)



class SpikeWaveBuffer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPIKEWAVEBUFFER
  
  # @@protoc_insertion_point(class_scope:SpikeWaveBuffer)

# @@protoc_insertion_point(module_scope)
